- name: nodebrew install
  shell: curl -L git.io/nodebrew | perl - setup
- name: write ~/.bashrc
  shell: echo "export PATH=$HOME/.nodebrew/current/bin:$PATH" >> ~/.bashrc
- name: source ~/.bashrc
  shell: bash -lc "source ~/.bashrc"
- name: node and npm install
  shell: bash -lc "nodebrew install-binary '{{ target_version }}'"
- name: set node version
  shell: bash -lc "nodebrew use '{{ target_version }}'"